#!/bin/sh
set -e

lb config noauto \
    --architectures amd64 \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --bootloaders "grub-pc grub-efi" \
    --bootappend-live "boot=live components quiet splash loglevel=3 username=cipher user-password=cipher" \
    --chroot-squashfs-compression-type "zstd" \
    "${@}"
