---
backend: apt

skip_if_missing: true

operations:
  - try_remove:
      - live-boot
      - live-config
      - live-tools
      - live-task-localisation
      - live-task-recommended
      - calamares-settings-debian
