monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.pci-0000_00_05.0" }
    ]
    actions = {
      update-props = {
        device.profile = "output:analog-stereo"
        api.acp.auto-profile = false
        api.acp.auto-port = false
      }
    }
  }
]
